#!/bin/sh

# Style
REDBOLD="\033[0;31;1m"
GREENBOLD="\033[0;32;1m"
BOLD="\033[1m"
NORMAL="\033[0m"

echo "$BOLD Running pre-commit hook... $NORMAL"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# Check branch name is correct
LC_ALL=C
local_branch="$(git rev-parse --abbrev-ref HEAD)"

# shellcheck disable=SC2039
if [[ $local_branch =~ ^(master|main|dev)$ ]]; then
  echo "$REDBOLD Cannot commit to master/main/dev"
  exit 1
fi

valid_branch_regex="^(feature|bugfix|improvement|library|release|hotfix|tools)\/[a-z0-9._-]+$"
# shellcheck disable=SC2039
if [[ ! $local_branch =~ $valid_branch_regex ]]; then
  echo "$REDBOLD Branch Name Check Failed $NORMAL"
  echo "There is something wrong with your branch name. Branch names in this project must adhere to this contract: $BOLD$valid_branch_regex$NORMAL."
  echo "Your commit will be rejected. Rename your branch to a valid name and try again."
  exit 1
fi

# Commit Message should not have non-ascii characters

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.

# Note that the use of brackets around a tr range is ok here, (it's
# even required, for portability to Solaris 10's /usr/bin/tr), since
# the square bracket bytes happen to fall in the designated range.
if test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
  echo "$REDBOLD non-ASCII characters not allowed in filenames $NORMAL"
  echo "This can cause problems if you want to work with people on other platforms."
  echo "Please Remove the non-ascii character"
  exit 1
fi
echo "$GREENBOLD Branch validation successful $NORMAL"

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached "$against" --

exit 0